imports:
    - { resource: "services/decorator.yml" }
    - { resource: "services/controller.yml" }
    - { resource: "services/factory.yml" }

services:
    BitBag\SyliusMultiCartPlugin\Helper\ConvertAndFormatMoneyHelperInterface:
        alias: 'bitbag_sylius_multi_cart_plugin.helper.convert_and_format_money'

    bitbag_sylius_multi_cart_plugin.helper.convert_and_format_money:
        class: BitBag\SyliusMultiCartPlugin\Helper\ConvertAndFormatMoneyHelper
        arguments:
            - '@sylius.context.shopper'
            - '@sylius.currency_converter'
            - '@sylius.money_formatter'
        tags:
            - { name: 'controller.service_arguments' }
