imports:
    - { resource: "services/decorator.yml" }
    - { resource: "services/controller.yml" }
    - { resource: "services/factory.yml" }

services:
    BitBag\SyliusMultiCartPlugin\MoneyConverter\MoneyConverter:
        alias: 'bitbag_sylius_multi_cart_plugin.converter.money_converter'

    bitbag_sylius_multi_cart_plugin.converter.money_converter:
        class: BitBag\SyliusMultiCartPlugin\MoneyConverter\MoneyConverter
        arguments:
            - '@sylius.context.shopper'
            - '@sylius.currency_converter'
            - '@sylius.money_formatter'
        tags:
            - { name: 'controller.service_arguments' }

    BitBag\SyliusMultiCartPlugin\MoneyFormatter\MoneyFormatter:
        alias: 'bitbag_sylius_multi_cart_plugin.formatter.money_formatter'

    bitbag_sylius_multi_cart_plugin.formatter.money_formatter:
        class: BitBag\SyliusMultiCartPlugin\MoneyFormatter\MoneyFormatter
        arguments:
            - '@sylius.money_formatter'
            - '@sylius.context.shopper'
            - '@bitbag_sylius_multi_cart_plugin.converter.money_converter'
        tags:
            - { name: 'controller.service_arguments' }
