imports:
    - { resource: "services/decorator.yml" }
    - { resource: "services/controller.yml" }
    - { resource: "services/factory.yml" }

services:
    BitBag\SyliusMultiCartPlugin\Helper\FormatMoneyTransformer:
        alias: 'bitbag_sylius_multi_cart_plugin.transformer.format_money_transformer'

    bitbag_sylius_multi_cart_plugin.transformer.format_money_transformer:
        class: BitBag\SyliusMultiCartPlugin\Transformer\FormatMoneyTransformer
        arguments:
            - '@sylius.context.shopper'
            - '@sylius.currency_converter'
            - '@sylius.money_formatter'
        tags:
            - { name: 'controller.service_arguments' }
