# Delete these routes and define your own shop routes here

bit_bag_sylius_multi_cart_plugin_new_cart:
    path: /cart/new/{route}
    methods: [GET, POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.new_cart::newAction
#        _sylius:
#            route: $route

#sylius_shop_partial_cart_summary:
#    path: /summary
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.order:widgetAction
#        _sylius:
#            template: $template