# Delete these routes and define your own shop routes here

bit_bag_sylius_multi_cart_plugin_show_carts:
    path: /carts/show
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.show_carts

bit_bag_sylius_multi_cart_plugin_new_cart:
    path: /cart/new/{route}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.new_cart

bit_bag_sylius_multi_cart_plugin_change_active_cart:
    path: /cart/change-active-cart/{cartNumber}/{route}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.change_active_cart

bit_bag_sylius_multi_cart_plugin_delete_cart:
    path: /cart/delete/{cartNumber}/{route}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.delete_cart

#sylius_shop_partial_cart_summary:
#    path: /summary
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.order:widgetAction
#        _sylius:
#            template: $template