bit_bag_sylius_multi_cart_plugin_show_carts:
    path: /carts/show
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.show_carts

bit_bag_sylius_multi_cart_plugin_new_cart:
    path: /cart/new/{route}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.new_cart

bit_bag_sylius_multi_cart_plugin_change_active_cart:
    path: /ajax/cart/change-active-cart/{cartNumber}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.change_active_cart

bit_bag_sylius_multi_cart_plugin_ajax_cart:
    path: /ajax/cart-contents
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_cart

bit_bag_sylius_multi_cart_plugin_get_active_cart:
    path: /ajax/cart/get-active-cart
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.get_active_cart

bit_bag_sylius_multi_cart_plugin_delete_cart:
    path: /cart/delete/{cartNumber}/{route}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.delete_cart