bitbag_sylius_multi_cart_plugin_new_cart:
    path: /cart/new
    methods: [GET, POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_new_cart

bitbag_sylius_multi_cart_plugin_change_active_cart:
    path: /cart/change/{cartNumber}
    methods: [GET, POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_change_active_cart

bitbag_sylius_multi_cart_plugin_ajax_cart_content:
    path: /cart-contents
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_cart_content

bitbag_sylius_multi_cart_plugin_ajax_get_active_cart:
    path: /cart/get-active
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.get_active_cart

bitbag_sylius_multi_cart_plugin_delete_cart:
    path: /cart/delete/{cartNumber}
    methods: [GET, POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_delete_cart
