bit_bag_sylius_multi_cart_plugin_new_cart:
    path: /cart/new
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_new_cart

bit_bag_sylius_multi_cart_plugin_change_active_cart:
    path: /cart/change/{cartNumber}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_change_active_cart

bit_bag_sylius_multi_cart_plugin_ajax_cart_content:
    path: /cart-contents
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_cart_content

bit_bag_sylius_multi_cart_plugin_ajax_get_active_cart:
    path: /cart/get-active
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.get_active_cart

bit_bag_sylius_multi_cart_plugin_delete_cart:
    path: /cart/delete/{cartNumber}
    methods: [POST]
    defaults:
        _controller: bitbag_sylius_multi_cart_plugin.controller.ajax_delete_cart
